version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - '5173:5173'
    volumes:
      - ./frontend:/app
      - ./shared:/shared
      - /app/node_modules
    env_file:
      - ./frontend/.env
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm run dev
    depends_on:
      - backend
    networks:
      - tripoker_network

  backend:
    build: ./backend
    ports:
      - '3001:3001'
    volumes:
      - ./backend:/app
      - ./shared:/shared
      - /app/node_modules
    env_file:
      - ./backend/.env
    environment:
      - PORT=3001
    command: ["bash", "/wait-for-it.sh", "db", "3306", "npm", "start"]
    depends_on:
      - db
    networks:
      - tripoker_network

  db:
    image: mysql:8
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE:      ${MYSQL_DATABASE}
      MYSQL_USER:          ${MYSQL_USER}
      MYSQL_PASSWORD:      ${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - tripoker_network

volumes:
  db_data:

networks:
  tripoker_network:
    driver: bridge
